### ISSUE TITLE
[Bug] 404 when clicking "add" button

### ISSUE THREAD

**Issue by 1chooo** [leerob/next-music-player#1]
When I try to add a new playlist, I get a 404 error after clicking the 'Add' button.

### Recording

https://github.com/user-attachments/assets/1c0ae4f1-8aab-4fc6-8387-a4f0792f7496

**Comment by leerob** [comment]
Indeed, right now this only works locally (so I don't have to reset the prod DB every time 😄)

I'll find a better solution.

**Comment by 1chooo** [comment]
> Indeed, right now this only works locally (so I don't have to reset the prod DB every time 😄)
> 
> I'll find a better solution.

That makes sense! Keeping it local for now sounds like a good idea 😄. Thank you a lot!!!

**Comment by leerob** [comment]
Made the buttons disabled in production to improve this!
